server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: booking-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/booking_db}
    username: ${SPRING_DATASOURCE_USERNAME:booking_user}
    password: ${SPRING_DATASOURCE_PASSWORD:booking_pass}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    issuer: ${JWT_ISSUER:event-ticketing-gateway}
    secret: ${JWT_SECRET:event-ticketing-development-secret-32}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

services:
  payment:
    base-url: ${PAYMENT_SERVICE_URL:http://localhost:8082}

messaging:
  exchanges:
    payment-events: ${PAYMENT_EVENTS_EXCHANGE:payment-events}
    booking-events: ${BOOKING_EVENTS_EXCHANGE:booking-events}
  queues:
    payment-completed: ${PAYMENT_COMPLETED_QUEUE:booking.payment-completed}
